stages:
  data-ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data-cleaning:
    cmd: python src/data/clean_dataset.py
    deps:
    - data/raw
    - src/data/clean_dataset.py
    outs:
    - data/cleaned
  feature-selection:
    cmd: python src/features/build_features.py
    deps:
    - data/cleaned
    - src/data/features/build_features.py
    outs:
    - data/interim
  data-preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/interim
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  model-training:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - src/models/train_model.py
    outs:
    - models
  model-evaluation:
    cmd: python src/models/evaluate_model.py
    deps:
    - models
    - src/models/evaluate_model.py
    outs:
    - reports/experiment_info.json
    metrics:
    - reports/evaluation_metrics.json
